-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_establishments" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "description" TEXT,
    "address" TEXT NOT NULL,
    "city" TEXT,
    "postalCode" TEXT,
    "country" TEXT NOT NULL DEFAULT 'France',
    "latitude" REAL,
    "longitude" REAL,
    "phone" TEXT,
    "whatsappPhone" TEXT,
    "messengerUrl" TEXT,
    "email" TEXT,
    "website" TEXT,
    "instagram" TEXT,
    "facebook" TEXT,
    "activities" JSONB,
    "specialites" TEXT NOT NULL DEFAULT '',
    "motsClesRecherche" TEXT,
    "services" JSONB,
    "ambiance" JSONB,
    "paymentMethods" JSONB,
    "horairesOuverture" JSONB,
    "prixMoyen" REAL,
    "capaciteMax" INTEGER,
    "accessibilite" BOOLEAN NOT NULL DEFAULT false,
    "parking" BOOLEAN NOT NULL DEFAULT false,
    "terrasse" BOOLEAN NOT NULL DEFAULT false,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "subscription" TEXT NOT NULL DEFAULT 'FREE',
    "ownerId" TEXT NOT NULL,
    "rejectionReason" TEXT,
    "rejectedAt" DATETIME,
    "lastModifiedAt" DATETIME,
    "viewsCount" INTEGER NOT NULL DEFAULT 0,
    "clicksCount" INTEGER NOT NULL DEFAULT 0,
    "avgRating" REAL,
    "totalComments" INTEGER NOT NULL DEFAULT 0,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "tiktok" TEXT,
    "youtube" TEXT,
    "imageUrl" TEXT,
    "priceMax" REAL,
    "priceMin" REAL,
    "informationsPratiques" JSONB,
    "googlePlaceId" TEXT,
    "googleBusinessUrl" TEXT,
    "enriched" BOOLEAN NOT NULL DEFAULT false,
    "smartEnrichmentData" JSONB,
    "googleRating" REAL,
    "googleReviewCount" INTEGER,
    "envieTags" JSONB,
    "theForkLink" TEXT,
    "uberEatsLink" TEXT,
    "enrichmentData" JSONB,
    "priceLevel" INTEGER,
    "specialties" JSONB,
    "atmosphere" JSONB,
    "accessibility" JSONB,
    "accessibilityDetails" JSONB,
    "detailedServices" JSONB,
    "clienteleInfo" JSONB,
    "detailedPayments" JSONB,
    "childrenServices" JSONB,
    CONSTRAINT "establishments_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "professionals" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
INSERT INTO "new_establishments" ("accessibilite", "accessibility", "accessibilityDetails", "activities", "address", "ambiance", "atmosphere", "avgRating", "capaciteMax", "childrenServices", "city", "clicksCount", "clienteleInfo", "country", "createdAt", "description", "detailedPayments", "detailedServices", "email", "enriched", "enrichmentData", "envieTags", "facebook", "googleBusinessUrl", "googlePlaceId", "googleRating", "googleReviewCount", "horairesOuverture", "id", "imageUrl", "informationsPratiques", "instagram", "lastModifiedAt", "latitude", "longitude", "messengerUrl", "motsClesRecherche", "name", "ownerId", "parking", "paymentMethods", "phone", "postalCode", "priceLevel", "priceMax", "priceMin", "prixMoyen", "rejectedAt", "rejectionReason", "services", "slug", "smartEnrichmentData", "specialites", "specialties", "status", "subscription", "terrasse", "theForkLink", "tiktok", "totalComments", "uberEatsLink", "updatedAt", "viewsCount", "website", "whatsappPhone", "youtube") SELECT "accessibilite", "accessibility", "accessibilityDetails", "activities", "address", "ambiance", "atmosphere", "avgRating", "capaciteMax", "childrenServices", "city", "clicksCount", "clienteleInfo", "country", "createdAt", "description", "detailedPayments", "detailedServices", "email", "enriched", "enrichmentData", "envieTags", "facebook", "googleBusinessUrl", "googlePlaceId", "googleRating", "googleReviewCount", "horairesOuverture", "id", "imageUrl", "informationsPratiques", "instagram", "lastModifiedAt", "latitude", "longitude", "messengerUrl", "motsClesRecherche", "name", "ownerId", "parking", "paymentMethods", "phone", "postalCode", "priceLevel", "priceMax", "priceMin", "prixMoyen", "rejectedAt", "rejectionReason", "services", "slug", "smartEnrichmentData", "specialites", "specialties", "status", "subscription", "terrasse", "theForkLink", "tiktok", "totalComments", "uberEatsLink", "updatedAt", "viewsCount", "website", "whatsappPhone", "youtube" FROM "establishments";
DROP TABLE "establishments";
ALTER TABLE "new_establishments" RENAME TO "establishments";
CREATE UNIQUE INDEX "establishments_slug_key" ON "establishments"("slug");
CREATE UNIQUE INDEX "establishments_ownerId_key" ON "establishments"("ownerId");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
